<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \MageSuite\GoogleApi\Block\ApiSettings $block */
$googleApiSettings = $block->getGoogleApiSettings();

if (!empty($googleApiSettings)) { ?>
    <span style="display: none;"
        id="google-api-settings"
        data-google-api-key="<?= $escaper->escapeHtmlAttr($googleApiSettings['key']) ?>"
        data-google-api-language="<?= $escaper->escapeHtmlAttr($googleApiSettings['language']) ?>"
        data-google-api-region="<?= $escaper->escapeHtmlAttr($googleApiSettings['region']) ?>">
    </span>
<?php }
